#!/usr/bin/env bash
# Bash script that makes /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Ngnix HTTP'
echo "Hello World" >/var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=rWEocmYxFbc permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" >/usr/share/nginx/html/index.html
sed -i '/server_name;/a error_page 404 /index.html;nlocation = /index.html {\root /usr/share/ngnix/html;\ninternal;\n}' /etc/nginx/sites-available/default
sudo service nginx restart