#!/usr/bin/env bash
#configures a brand new Ubuntu machine to the requirements asked in this task
sudo apt-get -y update
sudo apt-get -y install nginx
sed -i "/listen \[::\]:80 default_server;/a\add_header X-Served-By $(hostname);" /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=rWEocmYxFbc permanent;' /etc/nginx/sites-available/default
sed -i '/location \/ {$/a error_page 404 /error404.html;' /etc/nginx/sites-available/default
sudo service nginx restart