#!/usr/bin/env bash
#configures a brand new Ubuntu machine to the requirements asked in this task
sudo apt-get -y update
sudo apt-get -y install nginx
sed -i "/listen \[::\]:80 default_server;/a\add_header X-Served-By $(hostname);" /etc/nginx/sites-available/default
sudo service nginx restart