#!/usr/bin/env bash
# script that fixes the demanded script
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
