#!/usr/bin/env bash
# print "to  infinity and beyond" with some conditions

echo $$ >/var/run/myscript.pid
trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM
trap "rm /var/run/myscript.pid; exit" SIGQUIT
trap "echo Y U no love me?!" SIGINT
while true
do
        echo "To infinty and beyond"
        sleep 2
done
