#!/usr/bin/env bash
# fizzbuzz exercise
for (( count=1; count <=100; count++ ))
do
if (( count%15==0 ))
then
echo FizzBuzz
elif (( count%5==0 ))
then
echo Buzz
elif (( count%3==0 ))
then
echo Fizz
else
echo $count
fi
done
