#!/usr/bin/env bash
# display fizzbuzz program

for number in {1..100}
do
    if ((number % 15 == 0))
    then
        echo "FizzBuzz"
    elif ((number % 3 == 0))
    then
        echo "Fizz"
    elif ((number % 5 == 0))
    then
        echo "Buzz"
    else
        echo "$number"
    ((number++))
    fi
done
