#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but print "hi" at the 9th iteration

while ((counter < 10))
do
    echo "Best School"
    if [[ $counter -eq 8 ]];
    then
        echo "Hi"
    fi
    ((counter++))
done
