#!/usr/bin/env bash
# print Best School 10 times but bad luck on the 4th time and good luck on the 8th
counter=1
while ((counter <= 10))
do
if [ $counter -eq 4 ]
then
echo bad luck
elif [ $counter -eq 8 ]
then
echo good luck
else
echo Best School
fi
((counter++))
done
