#!/usr/bin/env bash
# print numbers from 1 to 20 and print bad luck from *** after the 4th,9th and 17th time
count=1
while (( count <= 20 ))
do
case $count in
5)
echo bad luck from China ;;
10)
echo bad luck from Japan ;;
18)
echo bad luck from Italy ;;
esac
echo $count
((count++))
done
